name: PHP Composer, Nette Tester & CS

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: test
        ports:
          - '13306:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Verify MySQL connection
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client
        sudo mysql --host 127.0.0.1 --port 13306 -uroot -ptest -e "SHOW DATABASES"
        sudo mysql -e 'CREATE DATABASE test;'        	

    - name: Run Nette Tester
      run: vendor/bin/tester -C tests/cases

    - name: Run Coding Standard
      run: vendor/modul-is/coding-standard/ecs check src
