name: Tests & CS ModulIS

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: test
        ports:
          - '13306:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Prepare MySQL connection
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client        
        sudo mysql --host 127.0.0.1 --port 13306 -uroot -ptest -e 'CREATE DATABASE test;'        	

    - name: Run Nette Tester
      run: vendor/bin/tester -C tests/cases

    - name: Run PHP Stan lvl 5
      run: vendor/bin/phpstan analyse --level 5 src

    - name: Run Coding Standard
      run: vendor/modul-is/coding-standard/ecs check src
